name: CI Pipeline

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compiler et tester le backend
        run: mvn -B clean verify --file backend/pom.xml

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer dépendances
        run: cd frontend && npm install

      - name: Vérifier que le front compile
        run: cd frontend && npm run lint
